package nuaa.dp.hole.dal.model;

import java.util.Date;

public class ProjectInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.gmt_create
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.project_name
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.remote_url
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private String remoteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.group_id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_info.source_path
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    private String sourcePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.id
     *
     * @return the value of t_project_info.id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.id
     *
     * @param id the value for t_project_info.id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.gmt_create
     *
     * @return the value of t_project_info.gmt_create
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.gmt_create
     *
     * @param gmtCreate the value for t_project_info.gmt_create
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.project_name
     *
     * @return the value of t_project_info.project_name
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.project_name
     *
     * @param projectName the value for t_project_info.project_name
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.remote_url
     *
     * @return the value of t_project_info.remote_url
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public String getRemoteUrl() {
        return remoteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.remote_url
     *
     * @param remoteUrl the value for t_project_info.remote_url
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setRemoteUrl(String remoteUrl) {
        this.remoteUrl = remoteUrl == null ? null : remoteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.group_id
     *
     * @return the value of t_project_info.group_id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.group_id
     *
     * @param groupId the value for t_project_info.group_id
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_info.source_path
     *
     * @return the value of t_project_info.source_path
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public String getSourcePath() {
        return sourcePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_info.source_path
     *
     * @param sourcePath the value for t_project_info.source_path
     *
     * @mbg.generated Fri Nov 27 20:37:49 CST 2020
     */
    public void setSourcePath(String sourcePath) {
        this.sourcePath = sourcePath == null ? null : sourcePath.trim();
    }
}