package nuaa.dp.hole.dal.model;

import java.util.Date;

public class ProjectDependent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.gmt_create
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.project_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.artifact_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private String artifactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.simple_name
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private String simpleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.status_code
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private Integer statusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.order_status
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_dependent.pom_content
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    private String pomContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.id
     *
     * @return the value of t_project_dependent.id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.id
     *
     * @param id the value for t_project_dependent.id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.gmt_create
     *
     * @return the value of t_project_dependent.gmt_create
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.gmt_create
     *
     * @param gmtCreate the value for t_project_dependent.gmt_create
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.project_id
     *
     * @return the value of t_project_dependent.project_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.project_id
     *
     * @param projectId the value for t_project_dependent.project_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.artifact_id
     *
     * @return the value of t_project_dependent.artifact_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public String getArtifactId() {
        return artifactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.artifact_id
     *
     * @param artifactId the value for t_project_dependent.artifact_id
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId == null ? null : artifactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.simple_name
     *
     * @return the value of t_project_dependent.simple_name
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.simple_name
     *
     * @param simpleName the value for t_project_dependent.simple_name
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.status_code
     *
     * @return the value of t_project_dependent.status_code
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.status_code
     *
     * @param statusCode the value for t_project_dependent.status_code
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.order_status
     *
     * @return the value of t_project_dependent.order_status
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.order_status
     *
     * @param orderStatus the value for t_project_dependent.order_status
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_dependent.pom_content
     *
     * @return the value of t_project_dependent.pom_content
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public String getPomContent() {
        return pomContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_dependent.pom_content
     *
     * @param pomContent the value for t_project_dependent.pom_content
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    public void setPomContent(String pomContent) {
        this.pomContent = pomContent == null ? null : pomContent.trim();
    }
}