package nuaa.dp.hole.dal.model;

import java.util.Date;

public class TaskChild {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.gmt_create
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.task_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.artifact_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private String artifactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.match_count
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private Integer matchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.match_history
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private Integer matchHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.order_status
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_child.found_versions
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    private String foundVersions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.id
     *
     * @return the value of t_task_child.id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.id
     *
     * @param id the value for t_task_child.id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.gmt_create
     *
     * @return the value of t_task_child.gmt_create
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.gmt_create
     *
     * @param gmtCreate the value for t_task_child.gmt_create
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.task_id
     *
     * @return the value of t_task_child.task_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.task_id
     *
     * @param taskId the value for t_task_child.task_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.artifact_id
     *
     * @return the value of t_task_child.artifact_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public String getArtifactId() {
        return artifactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.artifact_id
     *
     * @param artifactId the value for t_task_child.artifact_id
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId == null ? null : artifactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.match_count
     *
     * @return the value of t_task_child.match_count
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public Integer getMatchCount() {
        return matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.match_count
     *
     * @param matchCount the value for t_task_child.match_count
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setMatchCount(Integer matchCount) {
        this.matchCount = matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.match_history
     *
     * @return the value of t_task_child.match_history
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public Integer getMatchHistory() {
        return matchHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.match_history
     *
     * @param matchHistory the value for t_task_child.match_history
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setMatchHistory(Integer matchHistory) {
        this.matchHistory = matchHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.order_status
     *
     * @return the value of t_task_child.order_status
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.order_status
     *
     * @param orderStatus the value for t_task_child.order_status
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_child.found_versions
     *
     * @return the value of t_task_child.found_versions
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public String getFoundVersions() {
        return foundVersions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_child.found_versions
     *
     * @param foundVersions the value for t_task_child.found_versions
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    public void setFoundVersions(String foundVersions) {
        this.foundVersions = foundVersions == null ? null : foundVersions.trim();
    }
}