package nuaa.dp.hole.dal.model;

import java.util.Date;

public class TaskQueue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_queue.id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_queue.biz_id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    private Long bizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_queue.topic
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    private Integer topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_queue.ext_info
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_queue.next_time
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    private Date nextTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_queue.id
     *
     * @return the value of t_task_queue.id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_queue.id
     *
     * @param id the value for t_task_queue.id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_queue.biz_id
     *
     * @return the value of t_task_queue.biz_id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public Long getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_queue.biz_id
     *
     * @param bizId the value for t_task_queue.biz_id
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public void setBizId(Long bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_queue.topic
     *
     * @return the value of t_task_queue.topic
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public Integer getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_queue.topic
     *
     * @param topic the value for t_task_queue.topic
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public void setTopic(Integer topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_queue.ext_info
     *
     * @return the value of t_task_queue.ext_info
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_queue.ext_info
     *
     * @param extInfo the value for t_task_queue.ext_info
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_queue.next_time
     *
     * @return the value of t_task_queue.next_time
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_queue.next_time
     *
     * @param nextTime the value for t_task_queue.next_time
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }
}