spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cz.found.ai:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: super
    password: w3R@video
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1200000
      connection-timeout: 30000
      connection-test-query: SELECT 1

application:
  delayq:
    server: http://queue-test.youngfly.com.cn/
    origin: 101