package nuaa.dp.hole.dal.dao;

import java.util.List;
import nuaa.dp.hole.dal.model.ProjectDependent;
import nuaa.dp.hole.dal.model.ProjectDependentExample;
import org.apache.ibatis.annotations.Param;

public interface ProjectDependentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    long countByExample(ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int deleteByExample(ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int insert(ProjectDependent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int insertSelective(ProjectDependent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    List<ProjectDependent> selectByExampleWithBLOBs(ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    List<ProjectDependent> selectByExample(ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    ProjectDependent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProjectDependent record, @Param("example") ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectDependent record, @Param("example") ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByExample(@Param("record") ProjectDependent record, @Param("example") ProjectDependentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectDependent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProjectDependent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_dependent
     *
     * @mbg.generated Mon Nov 16 20:40:30 CST 2020
     */
    int updateByPrimaryKey(ProjectDependent record);
}