package nuaa.dp.hole.dal.dao;

import java.util.List;
import nuaa.dp.hole.dal.model.TaskQueue;
import nuaa.dp.hole.dal.model.TaskQueueExample;
import org.apache.ibatis.annotations.Param;

public interface TaskQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    long countByExample(TaskQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int deleteByExample(TaskQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int insert(TaskQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int insertSelective(TaskQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    List<TaskQueue> selectByExample(TaskQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    TaskQueue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int updateByExampleSelective(@Param("record") TaskQueue record, @Param("example") TaskQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int updateByExample(@Param("record") TaskQueue record, @Param("example") TaskQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int updateByPrimaryKeySelective(TaskQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_queue
     *
     * @mbg.generated Sat Jan 02 18:47:18 CST 2021
     */
    int updateByPrimaryKey(TaskQueue record);
}