package nuaa.dp.hole.dal.dao;

import java.util.List;
import nuaa.dp.hole.dal.model.TaskInfo;
import nuaa.dp.hole.dal.model.TaskInfoExample;
import org.apache.ibatis.annotations.Param;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    long countByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int deleteByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    List<TaskInfo> selectByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    TaskInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int updateByExample(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_info
     *
     * @mbg.generated Sun Nov 29 11:05:23 CST 2020
     */
    int updateByPrimaryKey(TaskInfo record);
}