package nuaa.dp.hole.dal.dao;

import java.util.List;
import nuaa.dp.hole.dal.model.TaskChild;
import nuaa.dp.hole.dal.model.TaskChildExample;
import org.apache.ibatis.annotations.Param;

public interface TaskChildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    long countByExample(TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int deleteByExample(TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int insert(TaskChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int insertSelective(TaskChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    List<TaskChild> selectByExampleWithBLOBs(TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    List<TaskChild> selectByExample(TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    TaskChild selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") TaskChild record, @Param("example") TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") TaskChild record, @Param("example") TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByExample(@Param("record") TaskChild record, @Param("example") TaskChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByPrimaryKeySelective(TaskChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(TaskChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_child
     *
     * @mbg.generated Wed Jan 06 21:44:33 CST 2021
     */
    int updateByPrimaryKey(TaskChild record);
}